/**
 * Reverse channel from the Chainlit backend into the OHIF viewer.
 *
 * The agent enqueues actions on the Python side (PENDING_ACTIONS in app.py);
 * we poll GET /capture/actions on a short interval and dispatch each action.
 *
 * v1 supports one action type:
 *   { type: "draw_annotation", toolName: "Length", viewportId,
 *     points_canvas_normalized: [[u1,v1],[u2,v2]], label, annotationUID }
 *
 * Normalized canvas coords (0..1, origin top-left) are converted to world
 * coords here via viewport.canvasToWorld() — keeping DICOM-geometry math out
 * of the Python side. The annotation is constructed manually (cachedStats: {}
 * pre-initialized) and inserted via annotation.state.addAnnotation(); the
 * MeasurementService listener surfaces it in the panel automatically (see
 * initMeasurementService.ts).
 */
import { getEnabledElementByViewportId } from '@cornerstonejs/core';
import { annotation as csAnnotation } from '@cornerstonejs/tools';

const POLL_INTERVAL_MS = 500;

type DrawAnnotationAction = {
  type: 'draw_annotation';
  toolName: 'Length';
  viewportId: string;
  points_canvas_normalized: [number, number][];
  label?: string;
  annotationUID?: string;
};

type Action = DrawAnnotationAction;

function _resolveChainlitUrl(): string {
  const fromLS =
    typeof window !== 'undefined' && window.localStorage?.getItem('askai.chainlitUrl');
  return (fromLS || 'http://localhost:8000').replace(/\/$/, '');
}

let _started = false;
let _actionCount = 0;

export function startActionPoller() {
  if (_started) return;
  _started = true;

  const url = `${_resolveChainlitUrl()}/capture/actions?session=default`;

  const poll = async () => {
    try {
      const r = await fetch(url, { method: 'GET' });
      if (!r.ok) return;
      const body = await r.json().catch(() => null);
      const actions: Action[] = (body && body.actions) || [];
      for (const action of actions) {
        _actionCount++;
        if (_actionCount === 1 || _actionCount % 10 === 0) {
          console.log(`[askai] action #${_actionCount} received`, action);
        }
        dispatch(action);
      }
    } catch {
      // Chainlit may be down between polls — stay quiet, retry on next tick.
    }
  };

  setInterval(poll, POLL_INTERVAL_MS);
  console.log(
    `[askai] action poller started — GET ${url} every ${POLL_INTERVAL_MS} ms`
  );

  (window as any).__askaiActionPoller = {
    pollOnce: poll,
    get actionCount() {
      return _actionCount;
    },
  };
}

function dispatch(action: Action) {
  if (action.type === 'draw_annotation') {
    drawAnnotation(action);
    return;
  }
  console.warn('[askai] unknown action type:', (action as any).type);
}

function drawAnnotation(action: DrawAnnotationAction) {
  const enabled = getEnabledElementByViewportId(action.viewportId);
  if (!enabled) {
    console.warn(
      `[askai] draw_annotation: no viewport with id "${action.viewportId}" — ` +
        `dropping action. (Enabled viewports: ${listViewportIds()})`
    );
    return;
  }
  const vp: any = enabled.viewport;
  const canvas: HTMLCanvasElement | null =
    typeof vp.getCanvas === 'function' ? vp.getCanvas() : null;
  if (!canvas) {
    console.warn('[askai] draw_annotation: viewport has no canvas');
    return;
  }

  // canvas.width/height are the actual pixel dimensions (post-DPR).
  // canvasToWorld expects canvas-pixel coords, not CSS pixels.
  const worldPoints = action.points_canvas_normalized.map(([u, v]) => {
    const px = u * canvas.width;
    const py = v * canvas.height;
    return vp.canvasToWorld([px, py]);
  });

  if (action.toolName === 'Length') {
    try {
      // Construct the annotation manually rather than calling
      // LengthTool.hydrate(): hydrate omits `data.cachedStats`, but the render
      // path indexes into `data.cachedStats[targetId]` without a guard, so a
      // hydrate-created annotation throws on first render. The DICOM-SR
      // hydration path uses this same manual pattern (see addSRAnnotation.ts).
      const FrameOfReferenceUID =
        typeof vp.getFrameOfReferenceUID === 'function'
          ? vp.getFrameOfReferenceUID()
          : undefined;
      const camera = typeof vp.getCamera === 'function' ? vp.getCamera() : null;
      const referencedImageId =
        typeof vp.getCurrentImageId === 'function' ? vp.getCurrentImageId() : undefined;

      const ann = {
        annotationUID: action.annotationUID,
        highlighted: false,
        isLocked: false,
        isVisible: true,
        invalidated: true,
        autoGenerated: true,
        metadata: {
          toolName: 'Length',
          viewPlaneNormal: camera?.viewPlaneNormal,
          viewUp: camera?.viewUp,
          FrameOfReferenceUID,
          referencedImageId,
        },
        data: {
          handles: {
            points: worldPoints,
            activeHandleIndex: null,
            textBox: {
              hasMoved: false,
              worldPosition: [0, 0, 0],
              worldBoundingBox: {
                topLeft: [0, 0, 0],
                topRight: [0, 0, 0],
                bottomLeft: [0, 0, 0],
                bottomRight: [0, 0, 0],
              },
            },
          },
          label: action.label,
          cachedStats: {},
        },
      };
      csAnnotation.state.addAnnotation(ann as any, vp.element);
      // Force a render so LengthTool._calculateCachedStats runs and fills mm.
      if (typeof vp.render === 'function') vp.render();
    } catch (e) {
      console.warn('[askai] draw_annotation (Length) failed:', e);
    }
    return;
  }

  console.warn(`[askai] draw_annotation: tool "${action.toolName}" not handled yet`);
}

function listViewportIds(): string {
  try {
    // Best-effort diagnostic; not all builds expose getEnabledElements at this
    // path. Wrapped in try/catch so a missing helper can't break the poller.
    const { getEnabledElements } = require('@cornerstonejs/core');
    return (getEnabledElements() || [])
      .map((e: any) => e?.viewport?.id)
      .filter(Boolean)
      .join(', ');
  } catch {
    return '?';
  }
}
